name: pr_check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true
        target: wasm32-unknown-unknown
        rustflags: "-W warnings"
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Build
      run: trunk build
    - name: Run tests
      run: cargo test
